// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQMo-inzmwx2l-A6eILHuMEBvrlKHoNuY',
    appId: '1:980151251492:web:c2c9dfd6cd90c329191eb1',
    messagingSenderId: '980151251492',
    projectId: 'pawgoda-app',
    authDomain: 'pawgoda-app.firebaseapp.com',
    storageBucket: 'pawgoda-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-TfYIBy9n0yP3-i7W95aI025_0t5AFhw',
    appId: '1:980151251492:android:312e6026713e3601191eb1',
    messagingSenderId: '980151251492',
    projectId: 'pawgoda-app',
    storageBucket: 'pawgoda-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzRLywcU0aM9JgZXToqdN5Vc25VqRFOo',
    appId: '1:980151251492:ios:72da8efb233f3c02191eb1',
    messagingSenderId: '980151251492',
    projectId: 'pawgoda-app',
    storageBucket: 'pawgoda-app.appspot.com',
    iosBundleId: 'utmspace.mobileappprogramming.pawgoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzRLywcU0aM9JgZXToqdN5Vc25VqRFOo',
    appId: '1:980151251492:ios:72da8efb233f3c02191eb1',
    messagingSenderId: '980151251492',
    projectId: 'pawgoda-app',
    storageBucket: 'pawgoda-app.appspot.com',
    iosBundleId: 'utmspace.mobileappprogramming.pawgoda',
  );

}